### ISSUE TITLE
Pet Not ReSpawning After Being Assimilated ( MutationCraft )

### ISSUE THREAD

**Issue by EternalSoul15** [Alex-the-666/DomesticationInnovation#172]
my pet got assimilated by another infected reature and so i had to put it down but its not respawning in the bed it set its respawn point at

**Comment by Daralexen05** [comment]
This might be a bug on Mutation Craft's end. It will most likely not be fixed though, because the mod is receiving a reboot from the ground up without MCreator. I just recommend uninstalling MutationCraft to see if your pet respawns.
