### ISSUE TITLE
Crash with Radium

### ISSUE THREAD

**Issue by Benjamboo** [Alex-the-666/DomesticationInnovation#28]
1.18.2,  Forge 40.1.0
Radium 0.7.10
Citadel 1.11.2
Domestic Innovation 1.3.0

Crash on launch, too soon to even create a proper crashlog.
[latest.log](https://github.com/Alex-the-666/DomesticationInnovation/files/8535247/latest.log)

This crash does NOT occur if Domestic Innovation is set to 1.2.0

**Comment by Benjamboo** [comment]
https://github.com/Asek3/Radium/issues/26#issue-1211570168  Radium github report.

**Comment by Alex-the-666** [comment]
fixed in 1.3.1
