### ISSUE TITLE
Mod instantly crashes game, unknown what the issue is

### ISSUE THREAD

**Issue by Gamershy** [Alex-the-666/DomesticationInnovation#37]
I ahve no mods modifying what this mod is changing, so I'm entirely unsure of what's breaking. The mods I'm using are:
Parcool
Ars Nouveau
PAtchouli
Flywheel
Create
Chisls n Bits
Physics Mod
Treechop
Sound Physics
Damage Tilt Fix
Camera Overhaul
InvMove
Inventory Hud+
Cloth Config
Citadel (required by this mod)
Curios
GeckoLib
Fast Leaf Decay
Optifine
and of course, this mod.
The game crashes without ever starting, saying an error occured at startup, and it may be due to an "invalid java runtime setup"
I genuinely can't think of what mod would be breaking this, as again, nothing adds new pets, or modifies vanilla pets or mobs. Any help?
Here's the log file as well, so you can dig through it. I do notice some references to Sodium in the file, but am unsure what those are referring to given this is supposedly a forge mod. I have no form of Sodium port installed, just Optifine.
[latest.log](https://github.com/Alex-the-666/DomesticationInnovation/files/8644473/latest.log)

**Comment by Alex-the-666** [comment]
[06May2022 22:34:29.338] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing mandatory dependencies: citadel

this tells us citadel is not installed correctly

**Comment by Gamershy** [comment]
That... makes no sense, I have citadel in my mod list. How can it be "improperly installed" when it's just drag and drop?
