### ISSUE TITLE
[1.5.0-1.19] Unable to run mod in development environment 

### ISSUE THREAD

**Issue by TelepathicGrunt** [Alex-the-666/DomesticationInnovation#56]
It appears DomesticationInnovation is doing some very dangerous and cursed stuff to modify vanilla pools at game load instead of mod loading.
https://paste.ee/p/IVr1R

The issue starts here where you are trying to access config values far too early and Forge crashes the dev environment. Forge is also warning that this will crash prod soon so you  ill need to change how you access the config before the breaking change is done
`TRANSFORMER/domesticationinnovation@1.5.0/com.github.alexthe668.domesticationinnovation.server.entity.DIVillagerRegistry.registerHouses(DIVillagerRegistry.java:43)`

Though I will say this, this mixin needs to go. Please. This is unneeded entirely and will always cause issues and is incompatible with datapacks adding to the pool files
https://github.com/Alex-the-666/DomesticationInnovation/blob/48bc2230088bccf5f8f67d607d0d74db1fd028b5/src/main/java/com/github/alexthe668/domesticationinnovation/mixin/PoolsMixin.java#L36

I strongly, strongly recommend following this gist I made for how to add to vanilla villages in a more safe and compatible way.
https://gist.github.com/TelepathicGrunt/4fdbc445ebcbcbeb43ac748f4b18f342

Please do not hesitate to ask any questions or if you need help with updating to this alternative way of adding to villages which should also solve your config issue as well.

**Comment by Alex-the-666** [comment]
should be fixed in the latest citadel version
